# Generated by Django 5.2.17 on 2026-08-13 15:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0015_sitesetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMRIssuanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Batch No must be alphanumeric, upper case, with no spaces.')], verbose_name='Batch No')),
                ('batch_type', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('VALIDATION', 'Validation'), ('RE_PROCESS', 'Re-Process'), ('ADDITIONAL', 'Additional'), ('TRIAL', 'Trial'), ('REWORK', 'Rework'), ('BLENDING', 'Blending'), ('PACKING', 'Packing')], max_length=20, verbose_name='Type of Batch')),
                ('process_order_no', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Process Order No must be numeric only, with no spaces.')], verbose_name='Process Order No')),
                ('master_document_no', models.CharField(max_length=100, verbose_name='Master Document No')),
                ('issued_date', models.DateField()),
                ('issued_time', models.TimeField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bmr_entries_issued', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bmr_entries_received', to=settings.AUTH_USER_MODEL, verbose_name='Issued To')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bmr_issuances', to='masters.product', verbose_name='Product Name')),
                ('production_block', models.ForeignKey(limit_choices_to={'area_type': 'BLOCK'}, on_delete=django.db.models.deletion.PROTECT, related_name='bmr_issuances', to='masters.area', verbose_name='Production Block')),
            ],
            options={
                'verbose_name': 'BMR Issuance Entry',
                'verbose_name_plural': 'BMR Issuance Entries',
                'ordering': ['-issued_date', '-issued_time', '-id'],
            },
        ),
    ]
