# Generated by Django 5.2.17 on 2026-08-13 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrissuanceentry',
            name='batch_no',
            field=models.CharField(help_text='Alphanumeric, upper case, no spaces. Must be unique — it cannot repeat.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$', 'Batch No must be alphanumeric, upper case, with no spaces.')], verbose_name='Batch No'),
        ),
    ]
