# Generated by Django 5.2.17 on 2026-08-13 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmr_log', '0002_alter_bmrissuanceentry_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmrissuanceentry',
            name='process_order_no',
            field=models.CharField(help_text='Numeric only, no spaces. Must be unique — it cannot repeat.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Process Order No must be numeric only, with no spaces.')], verbose_name='Process Order No'),
        ),
    ]
