# Generated by Django 5.2.17 on 2026-08-09 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0008_alter_equipment_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_snapshot', models.CharField(help_text='Area path captured at entry time so later hierarchy edits do not rewrite history.', max_length=200)),
                ('batch_no', models.CharField(blank=True, max_length=100, verbose_name='Batch No')),
                ('cleaning_sop_no', models.CharField(blank=True, max_length=100, verbose_name='Cleaning SOP No')),
                ('cleaning_type', models.CharField(blank=True, choices=[('A', 'Type A'), ('B', 'Type B'), ('G', 'Type G')], max_length=1, verbose_name='Type of Cleaning')),
                ('equipment_maintenance_sop_no', models.CharField(blank=True, max_length=100, verbose_name='Maintenance SOP No')),
                ('maintenance_frequency', models.CharField(blank=True, choices=[('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUAL', 'Annual'), ('BIANNUAL', 'Biannual'), ('OTHERS', 'Others')], max_length=20)),
                ('pm_process_order_no', models.CharField(blank=True, max_length=100, verbose_name='PM Process Order No')),
                ('qualification_protocol_no', models.CharField(blank=True, max_length=100, verbose_name='Qualification Protocol No')),
                ('remarks', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
                ('end_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_entries', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_entries', to='masters.equipment')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masters.product')),
                ('start_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_entries', to=settings.AUTH_USER_MODEL)),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.equipmentusagetype')),
            ],
            options={
                'verbose_name_plural': 'activity log entries',
                'ordering': ['-start_date', '-start_time', '-id'],
            },
        ),
    ]
