# Generated by Django 5.2.17 on 2026-08-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='maintenance_type',
            field=models.CharField(blank=True, choices=[('BREAKDOWN', 'Breakdown / Repair'), ('PREVENTIVE', 'Preventive Maintenance')], max_length=20, verbose_name='Maintenance Type'),
        ),
        migrations.AddField(
            model_name='activitylogentry',
            name='process_sub_type',
            field=models.CharField(blank=True, choices=[('REACTION', 'Reaction (Reactor Only)'), ('OTHER_EQUIPMENT', 'Equipment Other Than Reactor'), ('HOLDING', 'Holding of Mother Liquor / Distilled Solvent')], max_length=20, verbose_name='Process Sub Activity'),
        ),
        migrations.AlterField(
            model_name='activitylogentry',
            name='cleaning_type',
            field=models.CharField(blank=True, choices=[('A', 'Type A'), ('B', 'Type B'), ('Q', 'QA Certification'), ('G', 'Type G')], max_length=1, verbose_name='Type of Cleaning'),
        ),
    ]
