# Generated by Django 5.2.17 on 2026-08-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0002_activitylogentry_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='sap_document_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='SAP Document No'),
        ),
    ]
