# Generated by Django 5.2.17 on 2026-08-11 15:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0003_activitylogentry_sap_document_no'),
        ('masters', '0015_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Must match the sub-activity code used in code — e.g. REACTION, OTHER_EQUIPMENT, HOLDING, A, B, Q, G, BREAKDOWN, PREVENTIVE, QUALIFICATION.', max_length=20)),
                ('label', models.CharField(max_length=150)),
                ('during_state', models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('TO_BE_CLEANED_AFTER_MAINTENANCE', 'To Be Cleaned (After Maintenance)'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], max_length=32)),
                ('after_state', models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('TO_BE_CLEANED_AFTER_MAINTENANCE', 'To Be Cleaned (After Maintenance)'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], max_length=32)),
                ('allowed_prior_states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('TO_BE_CLEANED_AFTER_MAINTENANCE', 'To Be Cleaned (After Maintenance)'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], max_length=32), help_text='Equipment statuses this activity can be started from.', size=None)),
                ('usage_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_rules', to='masters.equipmentusagetype')),
            ],
            options={
                'verbose_name': 'Activity Rule',
                'ordering': ['usage_type__name', 'code'],
                'unique_together': {('usage_type', 'code')},
            },
        ),
    ]
