# Generated by Django 5.2.17 on 2026-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0005_seed_activity_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogentry',
            name='adhered_material_removed',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, verbose_name='Adhered Material Removed Within 24 Hours'),
        ),
    ]
