# Generated by Django 5.2.17 on 2026-08-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitylog', '0007_fix_cleaning_g_prior_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityruleconfig',
            name='expired_state',
            field=models.CharField(blank=True, choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('TO_BE_CLEANED_AFTER_MAINTENANCE', 'To Be Cleaned (After Maintenance)'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], help_text='Equipment state to move to once validity_days has elapsed. Required if validity_days is set.', max_length=32),
        ),
        migrations.AddField(
            model_name='activityruleconfig',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='How many days after_state remains valid before it automatically expires into expired_state. Blank means after_state never expires on its own.', null=True),
        ),
    ]
