# Generated by Django 5.2.17 on 2026-08-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C'), ('G', 'Type G'), ('TO_BE_CLEANED', 'To Be Cleaned')], max_length=20, unique=True)),
                ('validity_value', models.PositiveIntegerField()),
                ('validity_unit', models.CharField(choices=[('DAYS', 'Days'), ('WEEKS', 'Weeks')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['cleaning_type'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('campaign_length_days', models.PositiveIntegerField(blank=True, help_text='Max campaign duration in days per SOP 1035-A-0072.', null=True)),
                ('campaign_length_batches', models.PositiveIntegerField(blank=True, help_text='Max consecutive batches per campaign.', null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('BLOCK', 'Production Block'), ('STREAM', 'Area / Stream')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='masters.area')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_movable', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('BREAKDOWN', 'Breakdown'), ('NOT_IN_USE', 'Not in Use')], default='AVAILABLE', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='masters.area')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.equipmenttype')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['code'],
            },
        ),
    ]
