# Generated by Django 5.2.17 on 2026-08-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('UNDER_CALIBRATION', 'Under Calibration'), ('BREAKDOWN', 'Breakdown'), ('NOT_IN_USE', 'Not in Use')], default='AVAILABLE', max_length=20),
        ),
    ]
