# Generated by Django 5.2.17 on 2026-08-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_deactivate_extra_usage_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_type',
            field=models.CharField(choices=[('BLOCK', 'Production Block'), ('STREAM', 'Area / Stream'), ('LOCATION', 'Floor Location'), ('CUBICLE', 'Cubicle')], max_length=10),
        ),
    ]
