# Generated by Django 5.2.17 on 2026-08-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_area_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('UNDER_CALIBRATION', 'Under Calibration'), ('BREAKDOWN', 'Breakdown'), ('NOT_IN_USE', 'Not in Use')], default='AVAILABLE', max_length=30),
        ),
    ]
