# Generated by Django 5.2.17 on 2026-08-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_alter_equipment_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CleaningTypeRule',
        ),
    ]
