# Generated by Django 5.2.17 on 2026-08-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_delete_cleaningtyperule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='campaign_length_batches',
        ),
        migrations.RemoveField(
            model_name='product',
            name='campaign_length_days',
        ),
    ]
