# Generated by Django 5.2.17 on 2026-08-09 15:51

from django.db import migrations, models


def remap_removed_states(apps, schema_editor):
    """AVAILABLE and BREAKDOWN are being dropped from EquipmentState — neither
    ever appeared in the Activity Rules table, so any equipment still holding
    one of them moves to Idle (the new default / cycle entry point)."""
    Equipment = apps.get_model('masters', 'Equipment')
    Equipment.objects.filter(state__in=['AVAILABLE', 'BREAKDOWN']).update(state='NOT_IN_USE')


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_remove_product_campaign_length_batches_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_removed_states, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], default='NOT_IN_USE', max_length=30),
        ),
    ]
