# Generated by Django 5.2.17 on 2026-08-09 22:31

from django.db import migrations, models


def remap_to_be_cleaned_after_maintenance(apps, schema_editor):
    """Type G cleaning now requires TO_BE_CLEANED_AFTER_MAINTENANCE rather than
    the generic TO_BE_CLEANED, so equipment left "To Be Cleaned" by a
    completed Maintenance activity needs to move to the new state — otherwise
    it would wrongly offer Type A/B cleaning and never offer Type G."""
    Equipment = apps.get_model('masters', 'Equipment')
    ActivityLogEntry = apps.get_model('activitylog', 'ActivityLogEntry')

    for equipment in Equipment.objects.filter(state='TO_BE_CLEANED'):
        last_entry = (
            ActivityLogEntry.objects.filter(equipment=equipment, end_date__isnull=False)
            .order_by('-end_date', '-end_time', '-id')
            .select_related('usage_type')
            .first()
        )
        if last_entry and last_entry.usage_type.name == 'Maintenance':
            equipment.state = 'TO_BE_CLEANED_AFTER_MAINTENANCE'
            equipment.save(update_fields=['state'])


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0011_alter_equipment_state'),
        ('activitylog', '0002_activitylogentry_maintenance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.CharField(choices=[('IN_PROCESS', 'In-Process'), ('IN_USE', 'In Use'), ('TO_BE_PRESERVED', 'To Be Preserved'), ('UNDER_CLEANING', 'Under Cleaning'), ('TO_BE_CLEANED', 'To Be Cleaned'), ('TO_BE_CLEANED_AFTER_MAINTENANCE', 'To Be Cleaned (After Maintenance)'), ('CLEANED_TYPE_A', 'Cleaned Type A'), ('CLEANED_READY_FOR_QA', 'Cleaned and Ready for QA Certification'), ('UNDER_QA_CERTIFICATION', 'Under QA Certification'), ('CLEANED_AND_QA_CERTIFIED', 'Cleaned and QA Certified'), ('CLEANED_AFTER_MAINTENANCE', 'Cleaned After Maintenance'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('UNDER_QUALIFICATION', 'Under Qualification'), ('NOT_IN_USE', 'Idle')], default='NOT_IN_USE', max_length=32),
        ),
        migrations.RunPython(remap_to_be_cleaned_after_maintenance, migrations.RunPython.noop),
    ]
