# Generated by Django 5.2.17 on 2026-08-10 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_equipment_state_add_after_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='streams',
            field=models.ManyToManyField(blank=True, help_text='Streams this product is manufactured in.', limit_choices_to={'area_type': 'STREAM'}, related_name='products', to='masters.area'),
        ),
        migrations.CreateModel(
            name='ProductEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_no', models.CharField(blank=True, max_length=100, verbose_name='Procedure No')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='masters.equipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_links', to='masters.product')),
            ],
            options={
                'ordering': ['product__name', 'equipment__code'],
                'unique_together': {('product', 'equipment')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='products', through='masters.ProductEquipment', to='masters.equipment'),
        ),
    ]
