# Generated by Django 5.2.17 on 2026-08-11 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_product_streams_productequipment_product_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'unit of measurement',
                'verbose_name_plural': 'units of measurement',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_oq_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Major Qualification (OQ) Date'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='material_of_construction',
            field=models.CharField(blank=True, max_length=100, verbose_name='Material of Construction'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='total_surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='capacity_uom',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement for Capacity across all equipment of this type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.unitofmeasurement', verbose_name='Capacity UOM'),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='surface_area_uom',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement for Total Surface Area across all equipment of this type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='masters.unitofmeasurement', verbose_name='Total Surface Area UOM'),
        ),
    ]
