# Generated by Django 5.2.17 on 2026-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0015_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='productequipment',
            name='cleaning_sop_no',
            field=models.CharField(blank=True, help_text='SOP used to clean this equipment after running this product.', max_length=100, verbose_name='Cleaning SOP No'),
        ),
    ]
