# Generated by Django 5.2.17 on 2026-08-13 16:01

from django.db import migrations


def copy_procedure_no_into_cleaning_sop_no(apps, schema_editor):
    """Procedure No and Cleaning SOP No are the same document — carry over
    any Procedure No value into Cleaning SOP No before the column is dropped,
    so rows that only had a Procedure No aren't silently emptied out.
    """
    ProductEquipment = apps.get_model('masters', 'ProductEquipment')
    for pe in ProductEquipment.objects.exclude(procedure_no='').filter(cleaning_sop_no=''):
        pe.cleaning_sop_no = pe.procedure_no
        pe.save(update_fields=['cleaning_sop_no'])


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0016_productequipment_cleaning_sop_no'),
    ]

    operations = [
        migrations.RunPython(copy_procedure_no_into_cleaning_sop_no, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='productequipment',
            name='procedure_no',
        ),
    ]
