# Generated by Django 5.2.17 on 2026-08-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0017_merge_procedure_no_into_cleaning_sop_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productequipment',
            name='cleaning_sop_no',
            field=models.CharField(blank=True, help_text='SOP for running this product on this equipment and for cleaning it afterwards.', max_length=100, verbose_name='Cleaning SOP No'),
        ),
    ]
