# Generated by Django 5.2.17 on 2026-08-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0018_alter_productequipment_cleaning_sop_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='state_changed_at',
            field=models.DateTimeField(blank=True, help_text='When `state` last changed — the anchor point for cleaning validity expiry.', null=True),
        ),
    ]
