# Generated by Django 5.2.17 on 2026-08-09 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('masters', '0008_alter_equipment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_stream',
            field=models.ForeignKey(blank=True, help_text='Stream the Dashboard opens to by default — set automatically when a stream is picked there.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masters.area'),
        ),
    ]
