# Generated by Django 5.2.17 on 2026-08-17 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0022_seed_computerized_systems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareIncidentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_no', models.CharField(editable=False, max_length=20, unique=True)),
                ('logged_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(verbose_name='Brief Description of Issue')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('module_or_equipment', models.CharField(blank=True, max_length=200, verbose_name='Module / Inst. / Equip. / Workstation')),
                ('category', models.CharField(blank=True, choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=10)),
                ('validation_required', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'Not Applicable')], max_length=5, verbose_name='Any Validation / Performance Required')),
                ('closeout_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_logged', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='masters.computerizedsystem', verbose_name='Name of the Computerized System')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Software Incident Entry',
                'verbose_name_plural': 'Software Incident Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
