# Generated by Django 5.2.17 on 2026-08-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software_incident_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwareincidententry',
            name='incident_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
