# Generated by Django 5.2.17 on 2026-08-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software_incident_log', '0002_alter_softwareincidententry_incident_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softwareincidententry',
            name='module_or_equipment',
        ),
    ]
